### GET REQUEST FOR ALL LAPTOPS ON RENDER
GET https://cse341-project-two.onrender.com/localhost:8000/laptops

### GET REQUEST FOR ALL LAPTOPS ON RENDER
GET https://cse341-project-two.onrender.com/localhost:8000/laptops

### SWAGGER
GET https://cse341-project-two.onrender.com/api-docs/

### SWAGGER LOCALHOST
GET http://localhost:8000/api-docs/

### GET REQUEST FOR HELLO WORLD
GET http://localhost:8000/

# #############################
#### LOCAL HOST: LAPTOP REQUEST
###############################
### GET REQUEST FROM LOCAL HOST THAT SHOWS ALL LAPTOPS
// GET ALL LAPTOPS
GET http://localhost:8000/laptops

### GET REQUEST FROM LOCAL HOST THAT SHOWS ONE LAPTOP BY ID
// GET ONE LAPTOP
GET http://localhost:8000/contacts/66403e94a19a99e1e3e1c840

### POST REQUEST FROM LOCAL HOST TO CREATE A NEW LAPTOP
// POST NEW LAPTOP
POST http://localhost:8000/contacts HTTP/1.1
Content-Type: application/json

{
    "modelName": "Macbook Air M3",
    "brand": "Apple",
    "processor": "16-Core Neural Engine",
    "screenSize": "13.6",
    "installedRAM": "16 GB",
    "driveCapacity": "512 GB",
    "driveType": "SSD",
    "price": 1949
}

### PUT REQUEST FROM LOCAL HOST TO UPDATE LAPTOP BY ID
// UPDATE LAPTOP BY ID
PUT http://localhost:8000/contacts/66403e94a19a99e1e3e1c840 HTTP/1.1
Content-Type: application/json

{
    "modelName": "Macbook Air M3",
    "brand": "Apple",
    "processor": "16-Core Neural Engine",
    "screenSize": "13.6",
    "installedRAM": "16 GB",
    "driveCapacity": "512 GB",
    "driveType": "SSD",
    "price": 1949
}

### DELETE REQUEST FROM LOCAL HOST TO DELETE ONE LAPTOP BY ID
// DELETE LAPTOP BY ID
DELETE http://localhost:8000/contacts/6636f8a5c407ef093cb2fa99 HTTP/1.1


# #############################
#### LOCAL HOST: PHONE REQUEST
###############################
### GET REQUEST FROM LOCAL HOST THAT SHOWS ALL SMARTPHONES
// GET ALL SMARTHONES
GET http://localhost:8000/phones

### GET REQUEST FROM LOCAL HOST THAT SHOWS ONE SMARTPHONE BY ID
// GET ONE SMARTPHONE
GET http://localhost:3000/contacts/664040b4a19a99e1e3e1c843

### POST REQUEST FROM LOCAL HOST TO CREATE A NEW SMARTPHONE
// POST NEW SMARTPHONE
POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
    "model": "iPhone SE",
    "brand": "Apple",
    "screenSize": "4.7-inch",
    "capacity": "128 GB",
    "chip": "A15 Bionic Chip",
    "backCamera": "12 MP",
    "frontCamera": "7 MP",
    "price": 649
}

### PUT REQUEST FROM LOCAL HOST TO UPDATE SMARTPHONE BY ID
// UPDATE SMARTPHONE BY ID
PUT http://localhost:3000/contacts/66403e94a19a99e1e3e1c840 HTTP/1.1
Content-Type: application/json

{
    "model": "iPhone SE",
    "brand": "Apple",
    "screenSize": "4.7-inch",
    "capacity": "128 GB",
    "chip": "A15 Bionic Chip",
    "backCamera": "12 MP",
    "frontCamera": "7 MP",
    "price": 649
}

### DELETE REQUEST FROM LOCAL HOST TO DELETE ONE SMARTPHONE BY ID
// DELETE SMARTPHONE BY ID
DELETE http://localhost:3000/contacts/6636f8a5c407ef093cb2fa99 HTTP/1.1